dist: ubuntu

language: go

go:
- "1.19.x"

env:
  - GO111MODULE=on

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.49.0
  - cd server

install: 
  - go mod tidy

script:
  - go build -o bin/crasher cmd/crasher/main.go
  - go test -v -race ./...
  - golangci-lint run ./...

