// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/repositories/core_dumps_repository.go

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	reflect "reflect"
	entities "server/internal/app/entities"

	gomock "github.com/golang/mock/gomock"
)

// MockCoreDumpsRepository is a mock of CoreDumpsRepository interface.
type MockCoreDumpsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCoreDumpsRepositoryMockRecorder
}

// MockCoreDumpsRepositoryMockRecorder is the mock recorder for MockCoreDumpsRepository.
type MockCoreDumpsRepositoryMockRecorder struct {
	mock *MockCoreDumpsRepository
}

// NewMockCoreDumpsRepository creates a new mock instance.
func NewMockCoreDumpsRepository(ctrl *gomock.Controller) *MockCoreDumpsRepository {
	mock := &MockCoreDumpsRepository{ctrl: ctrl}
	mock.recorder = &MockCoreDumpsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoreDumpsRepository) EXPECT() *MockCoreDumpsRepositoryMockRecorder {
	return m.recorder
}

// AddCoreDump mocks base method.
func (m *MockCoreDumpsRepository) AddCoreDump(coreDump entities.CoreDump) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCoreDump", coreDump)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCoreDump indicates an expected call of AddCoreDump.
func (mr *MockCoreDumpsRepositoryMockRecorder) AddCoreDump(coreDump interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCoreDump", reflect.TypeOf((*MockCoreDumpsRepository)(nil).AddCoreDump), coreDump)
}

// DeleteCoreDump mocks base method.
func (m *MockCoreDumpsRepository) DeleteCoreDump(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCoreDump", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCoreDump indicates an expected call of DeleteCoreDump.
func (mr *MockCoreDumpsRepositoryMockRecorder) DeleteCoreDump(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCoreDump", reflect.TypeOf((*MockCoreDumpsRepository)(nil).DeleteCoreDump), id)
}

// GetCoreDumps mocks base method.
func (m *MockCoreDumpsRepository) GetCoreDumps() ([]entities.CoreDump, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoreDumps")
	ret0, _ := ret[0].([]entities.CoreDump)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoreDumps indicates an expected call of GetCoreDumps.
func (mr *MockCoreDumpsRepositoryMockRecorder) GetCoreDumps() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoreDumps", reflect.TypeOf((*MockCoreDumpsRepository)(nil).GetCoreDumps))
}
